<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-BDUVLNVT" failures="1" tests="4" name="suiteLevel_Listener.Class2" time="0.009" errors="0" timestamp="2024-01-03T16:12:30 IST" skipped="0">
  <testcase classname="suiteLevel_Listener.Class2" name="d" time="0.002">
    <system-out>
      <![CDATA[TC dstarted execution
Hi d is running
TC dis completed successfully]]>
    </system-out>
  </testcase> <!-- d -->
  <testcase classname="suiteLevel_Listener.Class2" name="e" time="0.002">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at suiteLevel_Listener.Class2.e(Class2.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[TC estarted execution
TC eFailed the execution]]>
    </system-out>
  </testcase> <!-- e -->
  <testcase classname="suiteLevel_Listener.Class2" name="f" time="0.003">
    <system-out>
      <![CDATA[TC fstarted execution
Hi f is running
TC fis completed successfully]]>
    </system-out>
  </testcase> <!-- f -->
  <testcase classname="suiteLevel_Listener.Class2" name="g" time="0.002">
    <system-out>
      <![CDATA[TC gstarted execution
Hi g is running
TC gis completed successfully]]>
    </system-out>
  </testcase> <!-- g -->
  <system-out>
    <![CDATA[TC bstarted execution
TC bFailed the execution
TC dstarted execution
Hi d is running
TC dis completed successfully
TC astarted execution
Hi a is running
TC ais completed successfully
TC cstarted execution
TC cskipped execution
TC dstarted execution
Hi d is running
TC dis completed successfully
TC estarted execution
TC eFailed the execution
TC fstarted execution
Hi f is running
TC fis completed successfully
TC gstarted execution
Hi g is running
TC gis completed successfully]]>
  </system-out>
</testsuite> <!-- suiteLevel_Listener.Class2 -->
