<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-BDUVLNVT" failures="1" tests="1" name="coverFoxTest.CF_TC555_Validate_Error_Msg_for_healthcare_policies" time="10.819" errors="0" timestamp="2024-01-04T12:59:22 IST" skipped="0">
  <testcase classname="coverFoxTest.CF_TC555_Validate_Error_Msg_for_healthcare_policies" name="validatePincodeErrorMsg" time="10.819">
    <failure message="The following asserts failed:
	Error msg not match,TC is failed expected [Please enter a valid pin1] but found [Please enter a valid pincode]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error msg not match,TC is failed expected [Please enter a valid pin1] but found [Please enter a valid pincode]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at coverFoxTest.CF_TC555_Validate_Error_Msg_for_healthcare_policies.validatePincodeErrorMsg(CF_TC555_Validate_Error_Msg_for_healthcare_policies.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[Taking screenshot
Saved screenshot at C:\Users\Ankita\Desktop\Velocity\Selenium\Screenshots\coverFoxTC555_Error_2024.01.04.12.59.19.png]]>
    </system-out>
  </testcase> <!-- validatePincodeErrorMsg -->
  <system-out>
    <![CDATA[Launching Browser
Taking screenshot
Saved screenshot at C:\Users\Ankita\Desktop\Velocity\Selenium\Screenshots\coverFoxTC555_Error_2024.01.04.12.59.19.png
Closing Browser]]>
  </system-out>
</testsuite> <!-- coverFoxTest.CF_TC555_Validate_Error_Msg_for_healthcare_policies -->
